### ISSUE TITLE
some request (i guess they go here?)

### ISSUE THREAD

**Issue by part207** [planqi/slashdiablo-maphack#70]
a few things i think would be nice to have in the default config
all skill warnings (can be disabled, its just a pain to add them all each time theres an update)
unhidden 3os crown/great helm/large sheild (for classic)
notifications for +2 class skill magic items (stoppable)(for classic)
aera level in the top right with game name/ping/ect

i just wanted to say thanks for all the hard work so far. this is really one of the best tools for d2 ive ever had the privilege of using.

**Comment by BeLikeLeBron** [comment]
Notifying for available stoppable items isn't really a thing, but you can configure your config.bh to show the desired itmes in a different more visible color, like purple. The area levels thing might not be too necessary as ilvl is easy enough to show on items and as soon as something drops you know that info.
concerning the others, it's mostly stuff to do with the config as opposed to Bh.dll. If you want to customize them without updates messing with them, you can add them to the end of Bh_settings.cfg instead of bh.cfg. Then when something like the Slash Launcher updates the config, it wont mess with your custom things. A good config right now is [M81's config ](https://github.com/youbetterdont/bhconfig/releases) which has most things classified with the new in-game filters and pings settings. 
I recommend adding these two lines to the end of your BH_settings.cfg file so you dont have to worry about them being overwritten with slash launcher updates:

//unhidden 3os crown/great helm/large sheild (for classic)
ItemDisplay[NMAG HELM !BAR SOCK=3]: %GRAY%T6%MAP% %NAME%%TIER-6%

//Purple color for +2 class skill magic items (shoppable)(for classic only, no druid, assassin +2 stuff)
ItemDisplay[ID MAG (CLSK0>1 OR CLSK1>1 OR CLSK2>1 OR CLSK3>1 OR CLSK4>1 OR CLSK5>1)]: %ORANGE%T1%MAP% %PURPLE%%NAME%%notify-8%

**Comment by part207** [comment]
i didnt know the bit about about adding it to config, thats actaully great. and as far as custom ones go for classic stuff, ive added my own. ill just paste the into the the config. i wanted aera level because on sorc i tend to just tele through whole zones without thinking, its nice to just glance and see if i should stop and kill or not. i tried %alvl% and %aeralevel% but they both dont work for where i want it. all in all, its allll good. keep up the great work!

**Comment by youbetterdont** [comment]
Hey guys. I just wanted to clarify something here.

You can't put ItemDisplay lines in BH_settings.cfg. That file is only for settings that are associated with the in-game menu.

Perhaps this could be changed, but it isn't the way I did it. It was much easier to just make them separate.
